config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    api_version(:module => "v1", :header => {:name => "version", :value => "1"}, defaults: {format: :json}) do
     resources :compositions
     resources :images
     post 'authenticate', to: 'authentication#authenticate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/composition.rb
class Composition < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class  ApiController < ApplicationController
    include ActionController::ImplicitRender
    include ActionView::Layouts

  end
end

app/controllers/api/v1/authentication_controller.rb
module Api::V1
    class AuthenticationController < ApiController
        skip_before_action :authenticate_request 

        def authenticate
            command = AuthenticateUser.call(params[:username], params[:password])
            if command.success?
                render json: { auth_token: command.result }
            else
                render json: { error: command.errors }, status: :unauthorized 
            end
        end
    end
end

app/controllers/api/v1/compositions_controller.rb
module Api::V1
  class CompositionsController < ApiController
    before_action :set_composition, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_request, only: [:index, :show, :create, :update]

    # GET /compositions
    # GET /compositions.json
    def index
      @compositions = Composition.all
    end

    # GET /compositions/1
    # GET /compositions/1.json
    def show
    end

    # GET /compositions/new
    def new
      @composition = Composition.new
    end

    # GET /compositions/1/edit
    def edit
    end

    # POST /compositions
    # POST /compositions.json
    def create
      @image = Image.create()
      @composition = Composition.create(composition_params)
      render 'show'
    end

    # PATCH/PUT /compositions/1
    # PATCH/PUT /compositions/1.json
    def update
      if @composition.update(composition_params)
        render 'show'
      else
      end
    end

    # DELETE /compositions/1
    # DELETE /compositions/1.json
    def destroy
      @composition.destroy
      head :no_content
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_composition
        @composition = Composition.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def composition_params
        params.require(:composition).permit(:name, :description, :dimension, :materials)
      end
  end
end

app/controllers/api/v1/images_controller.rb
module Api::V1
  class ImagesController < ApiController
    skip_before_action :authenticate_request, only: [:index, :show]

    # GET /images
    # GET /images.json
    def index
      @images = Image.all
    end

    # GET /images/1
    # GET /images/1.json
    def show
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Image.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def image_params
        params.require(:image).permit(:name, :description, :file)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
    include ActionController::ImplicitRender
    include ActionView::Layouts
    before_action :authenticate_request 

    attr_reader :current_user 

    private 
    def authenticate_request
        Rails.logger.info('authenticating request')
        @current_user = AuthorizeApiRequest.call(request.headers).result 
        render json: { error: 'Not Authorized' }, status: 401 unless @current_user 
    end 
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy]

  # GET /compositions
  # GET /compositions.json
  def index
    @compositions = Composition.all
  end

  # GET /compositions/1
  # GET /compositions/1.json
  def show
  end

  # GET /compositions/new
  def new
    @composition = Composition.new
  end

  # GET /compositions/1/edit
  def edit
  end

  # POST /compositions
  # POST /compositions.json
  def create
    @composition = Composition.new(composition_params)

    respond_to do |format|
      if @composition.save
        format.html { redirect_to @composition, notice: 'Composition was successfully created.' }
        format.json { render :show, status: :created, location: @composition }
      else
        format.html { render :new }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compositions/1
  # PATCH/PUT /compositions/1.json
  def update
    respond_to do |format|
      if @composition.update(composition_params)
        format.html { redirect_to @composition, notice: 'Composition was successfully updated.' }
        format.json { render :show, status: :ok, location: @composition }
      else
        format.html { render :edit }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compositions/1
  # DELETE /compositions/1.json
  def destroy
    @composition.destroy
    respond_to do |format|
      format.html { redirect_to compositions_url, notice: 'Composition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composition
      @composition = Composition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composition_params
      params.require(:composition).permit(:name, :description, :dimension, :materials, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_form.html.erb
<%= form_with(model: composition, local: true) do |form| %>
  <% if composition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(composition.errors.count, "error") %> prohibited this composition from being saved:</h2>

      <ul>
      <% composition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :composition_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :composition_description %>
  </div>

  <div class="field">
    <%= form.label :dimension %>
    <%= form.text_area :dimension, id: :composition_dimension %>
  </div>

  <div class="field">
    <%= form.label :materials %>
    <%= form.text_area :materials, id: :composition_materials %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :composition_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/compositions/edit.html.erb
<h1>Editing Composition</h1>

<%= render 'form', composition: @composition %>

<%= link_to 'Show', @composition %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compositions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dimension</th>
      <th>Materials</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compositions.each do |composition| %>
      <tr>
        <td><%= composition.name %></td>
        <td><%= composition.description %></td>
        <td><%= composition.dimension %></td>
        <td><%= composition.materials %></td>
        <td><%= composition.image %></td>
        <td><%= link_to 'Show', composition %></td>
        <td><%= link_to 'Edit', edit_composition_path(composition) %></td>
        <td><%= link_to 'Destroy', composition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Composition', new_composition_path %>

app/views/compositions/new.html.erb
<h1>New Composition</h1>

<%= render 'form', composition: @composition %>

<%= link_to 'Back', compositions_path %>

app/views/compositions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @composition.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @composition.description %>
</p>

<p>
  <strong>Dimension:</strong>
  <%= @composition.dimension %>
</p>

<p>
  <strong>Materials:</strong>
  <%= @composition.materials %>
</p>

<p>
  <strong>Image:</strong>
  <%= @composition.image %>
</p>

<%= link_to 'Edit', edit_composition_path(@composition) %> |
<%= link_to 'Back', compositions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>